#!/usr/bin/env python3
"""
Generate a Gmsh .geo file for the cantilever shell benchmark.

The shell mid-surface is a rectangle in the global X-Z plane.
Gmsh is later called via CLI inside the Docker container.
"""

from pathlib import Path


# ---------------------------------------------------------------------------
# Model parameters
# ---------------------------------------------------------------------------

L = 1000.0      # beam length [mm]
b = 100.0       # beam height [mm]

nx = 40         # elements along beam length
nz = 5          # elements over beam height

case_name = "cantilever_shell_gmsh"


def main() -> None:
    lab_dir = Path(__file__).resolve().parents[1]
    geo_dir = lab_dir / "geo"
    geo_dir.mkdir(exist_ok=True)

    geo_file = geo_dir / f"{case_name}.geo"

    # Number of points on transfinite curves:
    # nx elements need nx + 1 points.
    nx_points = nx + 1
    nz_points = nz + 1

    geo_text = f"""// Lab 003 — Gmsh cantilever shell benchmark
// Generated by python/generate_gmsh_geo.py
//
// Unit system:
// - Length: mm
//
// Shell mid-surface: X-Z plane, Y = 0

L = {L:.6f};
b = {b:.6f};

nx_points = {nx_points};
nz_points = {nz_points};

// Corner points
Point(1) = {{0, 0, -b/2, 1.0}};
Point(2) = {{L, 0, -b/2, 1.0}};
Point(3) = {{L, 0,  b/2, 1.0}};
Point(4) = {{0, 0,  b/2, 1.0}};

// Boundary curves
Line(1) = {{1, 2}}; // bottom edge, length direction
Line(2) = {{2, 3}}; // right/free edge, height direction
Line(3) = {{3, 4}}; // top edge, length direction
Line(4) = {{4, 1}}; // left/clamped edge, height direction

Curve Loop(1) = {{1, 2, 3, 4}};
Plane Surface(1) = {{1}};

// Structured quad mesh
Transfinite Curve {{1, 3}} = nx_points;
Transfinite Curve {{2, 4}} = nz_points;
Transfinite Surface {{1}} = {{1, 2, 3, 4}};
Recombine Surface {{1}};

// Physical groups
Physical Curve("FIXED_EDGE") = {{4}};
Physical Curve("FREE_EDGE") = {{2}};
Physical Surface("SHELL_SURFACE") = {{1}};

// Mesh settings
Mesh.ElementOrder = 1;
Mesh.RecombineAll = 1;
"""

    geo_file.write_text(geo_text, encoding="utf-8")

    print(f"Written: {geo_file}")
    print(f"Case name: {case_name}")
    print(f"Target mesh: nx={nx}, nz={nz}")
    print(f"Expected shell elements: {nx * nz}")


if __name__ == "__main__":
    main()
