#!/usr/bin/env python3
"""
Generate a CalculiX input file for a cantilever shell benchmark.

Unit system:
- Force: N
- Length: mm
- Stress: MPa = N/mm²
"""

from pathlib import Path


# ---------------------------------------------------------------------------
# Model parameters
# ---------------------------------------------------------------------------

L = 1000.0          # beam length [mm]
b = 100.0           # beam height [mm]
s = 20.0            # shell thickness [mm]

E = 71000.0         # Young's modulus [MPa]
nu = 0.3            # Poisson's ratio [-]

F_total = -1000.0   # total vertical load [N], negative global Z direction

nx = 40             # elements along beam length
nz = 5              # elements over beam height; gives two central free-end nodes


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def node_id(i: int, j: int) -> int:
    """Return node id for grid index i along length and j over height."""
    return i * (nz + 1) + j + 1


def chunks(values, size=12):
    for i in range(0, len(values), size):
        yield values[i:i + size]


def write_nset(file, name, values):
    file.write(f"*NSET, NSET={name}\n")
    for chunk in chunks(values):
        file.write(", ".join(str(v) for v in chunk) + "\n")


def analytical_tip_displacement() -> float:
    """
    Euler-Bernoulli cantilever tip displacement.

    I = s * b^3 / 12
    delta = F * L^3 / (3 * E * I)
    """
    I = s * b**3 / 12.0
    return abs(F_total) * L**3 / (3.0 * E * I)


# ---------------------------------------------------------------------------
# Build nodes and elements
# ---------------------------------------------------------------------------

nodes = []
for i in range(nx + 1):
    x = L * i / nx
    for j in range(nz + 1):
        z = -b / 2.0 + b * j / nz
        y = 0.0
        nodes.append((node_id(i, j), x, y, z))

elements = []
eid = 1
for i in range(nx):
    for j in range(nz):
        n1 = node_id(i, j)
        n2 = node_id(i + 1, j)
        n3 = node_id(i + 1, j + 1)
        n4 = node_id(i, j + 1)
        elements.append((eid, n1, n2, n3, n4))
        eid += 1

fixed_nodes = [node_id(0, j) for j in range(nz + 1)]
free_end_nodes = [node_id(nx, j) for j in range(nz + 1)]

# Select two free-end nodes closest to z = 0.
node_z = {nid: z for nid, _x, _y, z in nodes}
load_nodes = sorted(free_end_nodes, key=lambda nid: (abs(node_z[nid]), node_z[nid]))[:2]
load_per_node = F_total / len(load_nodes)


# ---------------------------------------------------------------------------
# Write CalculiX input file
# ---------------------------------------------------------------------------

lab_dir = Path(__file__).resolve().parents[1]
out_file = lab_dir / "input" / "cantilever_shell_static.inp"

with out_file.open("w", encoding="utf-8") as f:
    f.write("*HEADING\n")
    f.write("Lab 001 - Cantilever shell benchmark, static bending\n")
    f.write("Generated by python/generate_cantilever_shell_inp.py\n")
    f.write("\n")

    f.write("*NODE\n")
    for nid, x, y, z in nodes:
        f.write(f"{nid}, {x:.6f}, {y:.6f}, {z:.6f}\n")
    f.write("\n")

    f.write("*ELEMENT, TYPE=S4, ELSET=EALL\n")
    for eid, n1, n2, n3, n4 in elements:
        f.write(f"{eid}, {n1}, {n2}, {n3}, {n4}\n")
    f.write("\n")

    write_nset(f, "FIXED", fixed_nodes)
    f.write("\n")
    write_nset(f, "FREE_END", free_end_nodes)
    f.write("\n")
    write_nset(f, "LOADNODES", load_nodes)
    f.write("\n")

    f.write("*MATERIAL, NAME=ALUMINUM\n")
    f.write("*ELASTIC\n")
    f.write(f"{E:.6f}, {nu:.6f}\n")
    f.write("\n")

    f.write("*SHELL SECTION, ELSET=EALL, MATERIAL=ALUMINUM\n")
    f.write(f"{s:.6f}\n")
    f.write("\n")

    f.write("*BOUNDARY\n")
    f.write("FIXED, 1, 6, 0.\n")
    f.write("\n")

    f.write("*STEP\n")
    f.write("*STATIC\n")
    f.write("\n")

    f.write("*CLOAD\n")
    for nid in load_nodes:
        f.write(f"{nid}, 3, {load_per_node:.6f}\n")
    f.write("\n")

    f.write("*NODE FILE\n")
    f.write("U, RF\n")
    f.write("*EL FILE\n")
    f.write("S\n")
    f.write("\n")

    f.write("*NODE PRINT, NSET=LOADNODES\n")
    f.write("U\n")
    f.write("*NODE PRINT, NSET=FREE_END\n")
    f.write("U\n")
    f.write("\n")

    f.write("*EL PRINT, ELSET=EALL\n")
    f.write("S\n")
    f.write("\n")

    f.write("*END STEP\n")

print(f"Written: {out_file}")
print(f"Nodes: {len(nodes)}")
print(f"Elements: {len(elements)}")
print(f"Fixed nodes: {fixed_nodes}")
print(f"Load nodes: {load_nodes}")
print(f"Load per node: {load_per_node:.3f} N")
print(f"Analytical tip displacement: {analytical_tip_displacement():.4f} mm")
