#!/usr/bin/env python3
"""
Write CalculiX C3D8 input file for Lab 007 structured hex dogbone.

Input:
- mesh/structured_hex_nodes.csv
- mesh/structured_hex_elements.csv
- Lab 006 S355MC material include

Output:
- input/tensile_dogbone_iso6892_form1_c3d8_s355mc.inp
"""

from pathlib import Path
import csv
import math
import shutil


CASE_NAME = "tensile_dogbone_iso6892_form1_c3d8_s355mc"
DISPLACEMENT_U1_MM = 2.0
MATERIAL_NAME = "S355MC"


def read_nodes(nodes_csv):
    nodes = {}
    meta = {}

    with nodes_csv.open("r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            nid = int(row["nid"])
            x = float(row["x_mm"])
            y = float(row["y_mm"])
            z = float(row["z_mm"])
            nodes[nid] = (x, y, z)
            meta[nid] = (int(row["ix"]), int(row["iy"]), int(row["iz"]))

    return nodes, meta


def read_elements(elems_csv):
    elements = []

    with elems_csv.open("r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            eid = int(row["eid"])
            conn = tuple(int(row[f"n{i}"]) for i in range(1, 9))
            elements.append((eid, conn))

    return elements


def write_id_list(f, ids, per_line=12):
    ids = list(ids)
    for i in range(0, len(ids), per_line):
        f.write(", ".join(str(v) for v in ids[i:i + per_line]) + "\n")


def nearest_node(nodes, target):
    tx, ty, tz = target

    best_id = None
    best_d2 = float("inf")

    for nid, (x, y, z) in nodes.items():
        d2 = (x - tx) ** 2 + (y - ty) ** 2 + (z - tz) ** 2
        if d2 < best_d2:
            best_id = nid
            best_d2 = d2

    return best_id, nodes[best_id], math.sqrt(best_d2)


def main():
    lab_dir = Path(__file__).resolve().parents[1]
    repo_dir = lab_dir.parents[1]

    mesh_dir = lab_dir / "mesh"
    input_dir = lab_dir / "input"
    results_dir = lab_dir / "results"
    materials_dir = lab_dir / "materials" / "S355MC"

    input_dir.mkdir(exist_ok=True)
    results_dir.mkdir(exist_ok=True)
    materials_dir.mkdir(parents=True, exist_ok=True)

    nodes_csv = mesh_dir / "structured_hex_nodes.csv"
    elems_csv = mesh_dir / "structured_hex_elements.csv"

    lab006_material = repo_dir / "labs" / "006_tensile_bar_elastoplastic" / "materials" / "S355MC" / "s355mc_ccx_material.inc"
    local_material = materials_dir / "s355mc_ccx_material.inc"

    if not lab006_material.exists():
        raise FileNotFoundError(f"Missing Lab 006 material include: {lab006_material}")

    shutil.copyfile(lab006_material, local_material)

    nodes, meta = read_nodes(nodes_csv)
    elements = read_elements(elems_csv)

    xs = [p[0] for p in nodes.values()]
    ys = [p[1] for p in nodes.values()]
    zs = [p[2] for p in nodes.values()]

    x_min = min(xs)
    x_max = max(xs)
    y_max = max(ys)

    tol = 1.0e-9

    left_end = sorted(nid for nid, (x, y, z) in nodes.items() if abs(x - x_min) < tol)
    right_end = sorted(nid for nid, (x, y, z) in nodes.items() if abs(x - x_max) < tol)

    fix_yz_node, fix_yz_xyz, fix_yz_dist = nearest_node(nodes, (x_min, 0.0, 0.0))
    fix_z_node, fix_z_xyz, fix_z_dist = nearest_node(nodes, (x_min, y_max, 0.0))

    inp_file = input_dir / f"{CASE_NAME}.inp"
    summary_file = results_dir / "c3d8_input_summary.txt"

    with inp_file.open("w", encoding="utf-8") as f:
        f.write("*HEADING\n")
        f.write("Lab 007 - EN ISO 6892-1 flat dogbone tensile specimen, structured C3D8 S355MC\n")
        f.write("Generated by python/write_ccx_c3d8_inp.py\n")
        f.write("\n")

        f.write("*NODE, NSET=ALLNODES\n")
        for nid in sorted(nodes):
            x, y, z = nodes[nid]
            f.write(f"{nid}, {x:.9f}, {y:.9f}, {z:.9f}\n")
        f.write("\n")

        f.write("*ELEMENT, TYPE=C3D8, ELSET=EALL_SOLID\n")
        for eid, conn in elements:
            f.write(f"{eid}, " + ", ".join(str(n) for n in conn) + "\n")
        f.write("\n")

        f.write("*NSET, NSET=LEFT_END\n")
        write_id_list(f, left_end)
        f.write("*NSET, NSET=RIGHT_END\n")
        write_id_list(f, right_end)
        f.write("*NSET, NSET=FIX_YZ_NODE\n")
        write_id_list(f, [fix_yz_node])
        f.write("*NSET, NSET=FIX_Z_NODE\n")
        write_id_list(f, [fix_z_node])
        f.write("\n")

        f.write(local_material.read_text(encoding="utf-8"))
        if not local_material.read_text(encoding="utf-8").endswith("\n"):
            f.write("\n")
        f.write("\n")

        f.write("*SOLID SECTION, ELSET=EALL_SOLID, MATERIAL=S355MC\n")
        f.write("\n")

        f.write("*BOUNDARY\n")
        f.write("LEFT_END, 1, 1, 0.0\n")
        f.write("FIX_YZ_NODE, 2, 3, 0.0\n")
        f.write("FIX_Z_NODE, 3, 3, 0.0\n")
        f.write("\n")

        f.write("*STEP, NLGEOM\n")
        f.write("*STATIC\n")
        f.write("0.01, 1.0, 1e-05, 0.05\n")
        f.write("*BOUNDARY\n")
        f.write(f"RIGHT_END, 1, 1, {DISPLACEMENT_U1_MM:.9f}\n")
        f.write("\n")

        f.write("*NODE FILE, NSET=ALLNODES\n")
        f.write("U\n")
        f.write("*EL FILE\n")
        f.write("S, E, PEEQ\n")
        f.write("\n")

        f.write("*NODE PRINT, NSET=RIGHT_END\n")
        f.write("U, RF\n")
        f.write("*NODE PRINT, NSET=LEFT_END\n")
        f.write("RF\n")
        f.write("\n")

        f.write("*END STEP\n")

    summary = f"""Lab 007 — C3D8 CalculiX Input Summary
====================================

Case:
{CASE_NAME}

Input file:
{inp_file}

Material include copied from:
{lab006_material}

Local material include:
{local_material}

Mesh:
- nodes: {len(nodes)}
- C3D8 elements: {len(elements)}

Bounds:
- x: {min(xs):.6f} ... {max(xs):.6f} mm
- y: {min(ys):.6f} ... {max(ys):.6f} mm
- z: {min(zs):.6f} ... {max(zs):.6f} mm

Node sets:
- LEFT_END nodes: {len(left_end)}
- RIGHT_END nodes: {len(right_end)}
- FIX_YZ_NODE: {fix_yz_node} at {fix_yz_xyz}, distance to target {fix_yz_dist:.6e} mm
- FIX_Z_NODE: {fix_z_node} at {fix_z_xyz}, distance to target {fix_z_dist:.6e} mm

Boundary/loading:
- LEFT_END U1 = 0
- RIGHT_END U1 = {DISPLACEMENT_U1_MM:.6f} mm
- FIX_YZ_NODE U2/U3 = 0
- FIX_Z_NODE U3 = 0

Output:
- NODE FILE: U
- EL FILE: S, E, PEEQ
- NODE PRINT: U/RF on RIGHT_END, RF on LEFT_END
"""
    summary_file.write_text(summary, encoding="utf-8")
    print(summary)


if __name__ == "__main__":
    main()
