#!/usr/bin/env python3
"""
Generate a 3D Gmsh .geo file for the Lab 006 flat dogbone tensile specimen.

Target:
- Full 3D dogbone volume
- Thickness a0
- Quadratic tetrahedral mesh later
- CalculiX element target: C3D10
"""

from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).resolve().parent))

from specimen_design import SpecimenGeometry, smoothstep_min_radius


CASE_NAME = "tensile_dogbone_iso6892_form1_3d"


def smoothstep(t: float) -> float:
    return 6.0 * t**5 - 15.0 * t**4 + 10.0 * t**3


def transition_points(x0: float, x1: float, y0: float, y1: float, n: int):
    pts = []
    for i in range(n):
        t = i / (n - 1)
        x = x0 + (x1 - x0) * t
        y = y0 + (y1 - y0) * smoothstep(t)
        pts.append((x, y))
    return pts


def main() -> None:
    lab_dir = Path(__file__).resolve().parents[1]
    geo_dir = lab_dir / "geo"
    geo_dir.mkdir(exist_ok=True)

    geom = SpecimenGeometry()

    half_lc = 0.5 * geom.parallel_length_Lc_mm
    half_b0 = 0.5 * geom.width_b0_mm
    half_B = 0.5 * geom.head_width_B_mm

    x_parallel_left = -half_lc
    x_parallel_right = half_lc

    x_left_transition_start = x_parallel_left - geom.transition_length_mm
    x_right_transition_end = x_parallel_right + geom.transition_length_mm

    x_left_end = x_left_transition_start - geom.grip_length_mm
    x_right_end = x_right_transition_end + geom.grip_length_mm

    total_length = x_right_end - x_left_end

    half_width_delta = half_B - half_b0
    estimated_radius = smoothstep_min_radius(
        delta_y=half_width_delta,
        length=geom.transition_length_mm,
    )

    # Mesh size choices for first nonlinear baseline.
    # Keep it moderate. C3D10 can become large quickly.
    lc_grip = 2.5
    lc_parallel = 1.2
    lc_transition = 1.0

    n_transition = 21

    # Through-thickness resolution:
    # For C3D10 tetra elements we do not get clean swept layers, but we limit
    # the tetra edge size so that at least about two element lengths fit through
    # the 2 mm sheet thickness.
    thickness_divisions_target = 2
    lc_thickness = geom.thickness_a0_mm / thickness_divisions_target

    top = []
    top.append((x_left_end, half_B))
    top.append((x_left_transition_start, half_B))

    top.extend(
        transition_points(
            x_left_transition_start,
            x_parallel_left,
            half_B,
            half_b0,
            n_transition,
        )[1:]
    )

    top.append((x_parallel_right, half_b0))

    top.extend(
        transition_points(
            x_parallel_right,
            x_right_transition_end,
            half_b0,
            half_B,
            n_transition,
        )[1:]
    )

    top.append((x_right_end, half_B))

    bottom = [(x, -y) for x, y in reversed(top)]
    all_points = top + bottom
    n_top = len(top)

    def char_len(x: float, y: float) -> float:
        if abs(y) <= half_b0 + 0.15 and x_parallel_left <= x <= x_parallel_right:
            return lc_parallel
        if x_left_transition_start <= x <= x_parallel_left or x_parallel_right <= x <= x_right_transition_end:
            return lc_transition
        return lc_grip

    geo = []
    geo.append('// Lab 006 — 3D ISO 6892-1 flat tensile dogbone specimen')
    geo.append('// Generated by python/generate_dogbone_3d_geo.py')
    geo.append('// Unit: mm')
    geo.append('')
    geo.append('SetFactory("OpenCASCADE");')
    geo.append('')
    geo.append(f'// a0 thickness = {geom.thickness_a0_mm:.6f} mm')
    geo.append(f'// b0 width = {geom.width_b0_mm:.6f} mm')
    geo.append(f'// L0 gauge length = {geom.gauge_length_L0_mm:.6f} mm')
    geo.append(f'// Lc parallel length = {geom.parallel_length_Lc_mm:.6f} mm')
    geo.append(f'// B head width = {geom.head_width_B_mm:.6f} mm')
    geo.append(f'// transition length = {geom.transition_length_mm:.6f} mm')
    geo.append(f'// grip length = {geom.grip_length_mm:.6f} mm')
    geo.append(f'// total length Lt = {total_length:.6f} mm')
    geo.append(f'// estimated smooth transition radius = {estimated_radius:.6f} mm')
    geo.append('')

    for pid, (x, y) in enumerate(all_points, start=1):
        geo.append(f'Point({pid}) = {{{x:.9f}, {y:.9f}, {-0.5 * geom.thickness_a0_mm:.9f}, {char_len(x, y):.6f}}};')

    geo.append('')

    curve_ids = []
    cid = 1
    for pid in range(1, len(all_points)):
        geo.append(f'Line({cid}) = {{{pid}, {pid + 1}}};')
        curve_ids.append(cid)
        cid += 1

    geo.append(f'Line({cid}) = {{{len(all_points)}, 1}};')
    curve_ids.append(cid)

    geo.append('')
    geo.append('Curve Loop(1) = {' + ', '.join(str(c) for c in curve_ids) + '};')
    geo.append('Plane Surface(1) = {1};')
    geo.append('')

    # Create full 3D volume by extruding the bottom surface through thickness.
    geo.append(f'out[] = Extrude {{0, 0, {geom.thickness_a0_mm:.9f}}} {{')
    geo.append('  Surface{1};')
    geo.append('};')
    geo.append('')

    # In this geometry:
    # Surface 1 is bottom surface.
    # out[0] is top surface.
    # out[1] is volume.
    geo.append('Physical Surface("BOTTOM_SURFACE") = {1};')
    geo.append('Physical Surface("TOP_SURFACE") = {out[0]};')
    geo.append('Physical Volume("DOGBONE_VOLUME") = {out[1]};')
    geo.append('')

    # We will identify left/right end nodes by x-coordinate in the converter.
    geo.append('// End faces are intentionally identified later by coordinate in the converter.')
    geo.append('')

    geo.append(f'// target thickness divisions = {thickness_divisions_target}')
    geo.append(f'// target thickness element size = {lc_thickness:.6f} mm')
    geo.append(f'Mesh.MeshSizeMin = {0.5 * lc_thickness:.6f};')
    geo.append(f'Mesh.MeshSizeMax = {lc_thickness:.6f};')
    geo.append('Mesh.Algorithm3D = 1;')
    geo.append('Mesh.ElementOrder = 2;')
    geo.append('Mesh.SecondOrderLinear = 1;')
    geo.append('Mesh.HighOrderOptimize = 0;')
    geo.append('Mesh.SaveAll = 1;')

    geo_file = geo_dir / f"{CASE_NAME}.geo"
    geo_file.write_text("\n".join(geo) + "\n", encoding="utf-8")

    print(f"Written: {geo_file}")
    print(f"Case name: {CASE_NAME}")
    print(f"Total length Lt: {total_length:.3f} mm")
    print(f"Thickness a0: {geom.thickness_a0_mm:.3f} mm")
    print(f"Target thickness divisions: {thickness_divisions_target}")
    print(f"Target thickness element size: {lc_thickness:.3f} mm")
    print(f"Reduced width b0: {geom.width_b0_mm:.3f} mm")
    print(f"Head width B: {geom.head_width_B_mm:.3f} mm")
    print(f"Estimated transition radius: {estimated_radius:.3f} mm")
    print(f"Radius target fulfilled: {estimated_radius >= geom.min_transition_radius_mm}")
    print(f"Contour points: {len(all_points)}")


if __name__ == "__main__":
    main()
