#!/usr/bin/env python3
"""
Generate a Gmsh .geo file for the Lab 006 flat dogbone tensile specimen.

This step creates only the 2D specimen outline. The geometry is centered at x=0.
Thickness is not meshed yet; it is part of the design definition and will be used
in later 3D / solid modelling steps.
"""

from pathlib import Path
import sys

# Allow importing specimen_design.py from the same folder.
sys.path.insert(0, str(Path(__file__).resolve().parent))

from specimen_design import SpecimenGeometry, smoothstep_min_radius


CASE_NAME = "tensile_dogbone_iso6892_form1"


def smoothstep(t: float) -> float:
    """C2 smooth transition from 0 to 1."""
    return 6.0 * t**5 - 15.0 * t**4 + 10.0 * t**3


def transition_points(x0: float, x1: float, y0: float, y1: float, n: int):
    """Create smooth transition points from (x0, y0) to (x1, y1)."""
    pts = []
    for i in range(n):
        t = i / (n - 1)
        x = x0 + (x1 - x0) * t
        y = y0 + (y1 - y0) * smoothstep(t)
        pts.append((x, y))
    return pts


def main() -> None:
    lab_dir = Path(__file__).resolve().parents[1]
    geo_dir = lab_dir / "geo"
    geo_dir.mkdir(exist_ok=True)

    geom = SpecimenGeometry()

    half_lc = 0.5 * geom.parallel_length_Lc_mm
    half_b0 = 0.5 * geom.width_b0_mm
    half_B = 0.5 * geom.head_width_B_mm

    x_parallel_left = -half_lc
    x_parallel_right = half_lc

    x_left_transition_start = x_parallel_left - geom.transition_length_mm
    x_right_transition_end = x_parallel_right + geom.transition_length_mm

    x_left_end = x_left_transition_start - geom.grip_length_mm
    x_right_end = x_right_transition_end + geom.grip_length_mm

    total_length = x_right_end - x_left_end

    half_width_delta = half_B - half_b0
    estimated_radius = smoothstep_min_radius(
        delta_y=half_width_delta,
        length=geom.transition_length_mm,
    )

    # Mesh sizes for first geometry preview.
    lc_edge = 2.5
    lc_transition = 1.25

    # Top contour from left to right.
    n_transition = 17

    top = []
    top.append((x_left_end, half_B))
    top.append((x_left_transition_start, half_B))

    left_transition = transition_points(
        x_left_transition_start,
        x_parallel_left,
        half_B,
        half_b0,
        n_transition,
    )[1:]

    top.extend(left_transition)
    top.append((x_parallel_right, half_b0))

    right_transition = transition_points(
        x_parallel_right,
        x_right_transition_end,
        half_b0,
        half_B,
        n_transition,
    )[1:]

    top.extend(right_transition)
    top.append((x_right_end, half_B))

    # Bottom contour is mirrored and goes right to left to close the loop.
    bottom = [(x, -y) for x, y in reversed(top)]

    all_points = top + bottom

    # Important point indices for physical edges.
    # 1-based Gmsh point IDs.
    n_top = len(top)
    left_top_id = 1
    left_bottom_id = len(all_points)
    right_top_id = n_top
    right_bottom_id = n_top + 1

    geo_lines = []
    geo_lines.append('// Lab 006 — ISO 6892-1 flat tensile dogbone specimen')
    geo_lines.append('// Generated by python/generate_dogbone_geo.py')
    geo_lines.append('// Unit: mm')
    geo_lines.append('')
    geo_lines.append(f'// a0 thickness = {geom.thickness_a0_mm:.6f} mm')
    geo_lines.append(f'// b0 width = {geom.width_b0_mm:.6f} mm')
    geo_lines.append(f'// L0 gauge length = {geom.gauge_length_L0_mm:.6f} mm')
    geo_lines.append(f'// Lc parallel length = {geom.parallel_length_Lc_mm:.6f} mm')
    geo_lines.append(f'// B head width = {geom.head_width_B_mm:.6f} mm')
    geo_lines.append(f'// transition length = {geom.transition_length_mm:.6f} mm')
    geo_lines.append(f'// grip length = {geom.grip_length_mm:.6f} mm')
    geo_lines.append(f'// total contour length Lt = {total_length:.6f} mm')
    geo_lines.append(f'// estimated smooth transition radius = {estimated_radius:.6f} mm')
    geo_lines.append('')

    for pid, (x, y) in enumerate(all_points, start=1):
        lc = lc_transition if abs(abs(y) - half_b0) < 3.5 else lc_edge
        geo_lines.append(f'Point({pid}) = {{{x:.9f}, {y:.9f}, 0.0, {lc:.6f}}};')

    geo_lines.append('')

    # Build contour as line segments. This is robust and keeps the sampled smooth outline exact.
    curve_ids = []
    cid = 1
    for pid in range(1, len(all_points)):
        geo_lines.append(f'Line({cid}) = {{{pid}, {pid + 1}}};')
        curve_ids.append(cid)
        cid += 1

    geo_lines.append(f'Line({cid}) = {{{len(all_points)}, 1}};')
    curve_ids.append(cid)

    geo_lines.append('')
    geo_lines.append('Curve Loop(1) = {' + ', '.join(str(c) for c in curve_ids) + '};')
    geo_lines.append('Plane Surface(1) = {1};')
    geo_lines.append('')

    # Physical groups.
    # Left and right end edges are the closing vertical edges at x = +/- Lt/2.
    left_edge_curve = curve_ids[-1]
    right_edge_curve = n_top

    geo_lines.append(f'Physical Curve("LEFT_GRIP_END") = {{{left_edge_curve}}};')
    geo_lines.append(f'Physical Curve("RIGHT_GRIP_END") = {{{right_edge_curve}}};')
    geo_lines.append('Physical Surface("DOGBONE_SURFACE") = {1};')
    geo_lines.append('')
    geo_lines.append('Mesh.Algorithm = 6;')
    geo_lines.append('Mesh.ElementOrder = 1;')
    geo_lines.append('Mesh.RecombineAll = 0;')
    geo_lines.append('Mesh.SaveAll = 1;')

    geo_file = geo_dir / f"{CASE_NAME}.geo"
    geo_file.write_text("\n".join(geo_lines) + "\n", encoding="utf-8")

    print(f"Written: {geo_file}")
    print(f"Case name: {CASE_NAME}")
    print(f"Total length Lt: {total_length:.3f} mm")
    print(f"Reduced width b0: {geom.width_b0_mm:.3f} mm")
    print(f"Head width B: {geom.head_width_B_mm:.3f} mm")
    print(f"Thickness a0: {geom.thickness_a0_mm:.3f} mm")
    print(f"Estimated smooth transition radius: {estimated_radius:.3f} mm")
    print(f"Radius target fulfilled: {estimated_radius >= geom.min_transition_radius_mm}")
    print(f"Number of contour points: {len(all_points)}")


if __name__ == "__main__":
    main()
